config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :diet_plans, only: [:new, :create, :destroy] do
    member do
      get 'confirm_deletion'
    end
  end

  resources :deportists, only: [:index, :new, :create] do
    resources :diet_plan_assignments
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  def to_s
    name
  end
end

app/models/deportist.rb
class Deportist < ActiveRecord::Base
  has_many :diet_plan_assignments, dependent: :destroy
  has_many :diet_plans, through: :diet_plan_assignments

  def main_diet_plan
    diet_plans.joins(:diet_plan_assignments).
      where(diet_plan_assignments: { priority: 0 }).first
  end

  def secondary_diet_plans
    diet_plans.joins(:diet_plan_assignments).
    where(diet_plan_assignments: { priority: 1 })
  end
end

app/models/diet_plan.rb
class DietPlan < ActiveRecord::Base
  TYPES = { 0 => 'Generico', 1 => 'Especifico' }
  DURATION_TYPES = { 0 => 'Dias', 1 => 'Semanas', 2 => 'Meses' }
  FREQUENCIES = { 0 => 'Diaria', 1 => 'Semanal', 2 => 'Quincenal', 3 => 'Mensual' }

  belongs_to :category

  has_many :diet_plan_assignments, dependent: :destroy
  has_many :deportists, through: :diet_plan_assignments
  has_many :meals, dependent: :destroy

  validates :name, uniqueness: true, presence: true, format: { with: /\A[a-zA-Z ]+\z/ }
  validates :goal, presence: true, format: { with: /\A[a-zA-Z ]+\z/ }
  validates :duration, presence: true, numericality: true
  validates :meals, presence: true

  validates :from_age, numericality: true, allow_nil: true
  validates :to_age, numericality: true, allow_nil: true
  validates :from_imc, numericality: true, allow_nil: true
  validates :to_imc, numericality: true, allow_nil: true

  accepts_nested_attributes_for :meals, :reject_if => :all_blank, :allow_destroy => true

  scope :search, -> (text) { where('name like ? or goal like ?', "%#{text}%", "%#{text}%") }

  def auto_generate_id
    "PD-#{rand.to_s[2..7]}"
  end

  def self.available_plan_types
    TYPES.map { |k,v| [v,k] }
  end

  def self.duration_types
    DURATION_TYPES.map { |k,v| [v,k] }
  end

  def self.frequencies
    FREQUENCIES.map { |k,v| [v,k] }
  end

  def age_range
    if from_age && to_age
      (from_age..to_age)
    end
  end

  def check_deportists_plans
    deportists.each do |d|
      return false if (d.diet_plans.count - 1).zero?
    end

    true
  end
end

app/models/diet_plan_assignment.rb
class DietPlanAssignment < ActiveRecord::Base
  PRIORITIES = { 0 => 'Principal', 1 => 'Secundario' }

  belongs_to :deportist
  belongs_to :diet_plan

  validate :age_range

  before_save :update_previous_main_plan

  def self.priorities
    PRIORITIES.map { |k,v| [v,k] }
  end

  def age_range
    if diet_plan.from_age && diet_plan.to_age
      if deportist.age < diet_plan.from_age || deportist.age > diet_plan.to_age
        errors.add(:deportist, "La edad del deportista debe estar entre #{diet_plan.from_age} y #{diet_plan.to_age} años.")
      end
    end
  end

  def update_previous_main_plan
    if deportist.main_diet_plan
      previous_main_assignment = deportist.diet_plan_assignments.where(priority: 0).first
      previous_main_assignment.update_columns(priority: 1)
    end
  end

end

app/models/meal.rb
class Meal < ActiveRecord::Base
  DAY_MOMENTS = { 0 => 'Mañana', 1 => 'Media Mañana', '2' => 'Almuerzo',
    '3' => 'Media Tarde', '4' => 'Tarde', '5' => 'Noche' }

  belongs_to :diet_plan

  def self.day_moments
    DAY_MOMENTS.map { |k,v| [v,k] }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/deportists_controller.rb
class DeportistsController < ApplicationController
  def index
    @deportists = Deportist.all
  end

  def new
    @deportist = Deportist.new
  end

  def create
    @deportist = Deportist.new(deportist_params)

    if @deportist.save
      redirect_to deportists_path
    else
      render :new
    end
  end

  private

  def deportist_params
    params.require(:deportist).permit(:name, :age, :imc, :number)
  end
end

app/controllers/diet_plan_assignments_controller.rb
class DietPlanAssignmentsController < ApplicationController
  def new
    @deportist = Deportist.find(params[:deportist_id])
    @diet_plan_assignment = DietPlanAssignment.new
    @diet_plans = DietPlan.all
  end

  def create
    @deportist = Deportist.find(params[:deportist_id])
    @diet_plan_assignment = DietPlanAssignment.new(plan_assignment_params)
    @diet_plan_assignment.deportist = @deportist
    @diet_plans = DietPlan.all

    @diet_plan_assignment.save

    render :new
  end

  private

  def plan_assignment_params
    params.require(:diet_plan_assignment).permit(:priority, :diet_plan_id)
  end
end

app/controllers/diet_plans_controller.rb
class DietPlansController < ApplicationController
  def new
    @diet_plan = DietPlan.new
    @categories = Category.all
  end

  def confirm_deletion
    @diet_plan = DietPlan.find(params[:id])
  end

  def create
    @diet_plan = DietPlan.new(diet_plan_params)
    @categories = Category.all

    if @diet_plan.save
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    @diet_plan = DietPlan.find(params[:id])

    if @diet_plan.check_deportists_plans
      @diet_plan.destroy

      redirect_to root_path
    else
      render :confirm_deletion
    end
  end

  private

  def diet_plan_params
    params.require(:diet_plan).permit(:name, :goal, :custom_id, :category_id, :plan_type,
      :from_age, :to_age, :duration, :duration_type, :frequency, :from_imc, :to_imc,
      meals_attributes: [:calories, :portion, :day, :day_moment, :_destroy])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @diet_plans = if params[:filter]
      DietPlan.search(params[:filter])
    else
      DietPlan.all
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/deportists/_deportist.html.erb
<tr>
  <td><%= deportist.number %></td>
  <td><%= deportist.name %></td>
  <td><%= deportist.age %></td>
  <td><%= deportist.imc %></td>

  <td>
    <%= link_to 'Asignar Plan Dietario', new_deportist_diet_plan_assignment_path(deportist),
      class: 'btn btn-sm btn-primary pull-right' %>
  </td>
</tr>

app/views/deportists/index.html.erb
<div class="row">
  <div class="col-md-4">
    <h3>Deportistas</h3>
  </div>
  <div class="col-md-4">
    <form method="get" action="/deportists" class="form-inline btn-nuevo" role="form">
      <div class="form-group">
        <div class="input-group">
          <input type="text" name="filter" value="<%= params[:filter] %>"
          class="form-control" placeholder="Buscar">
        </div>
      </div>

      <button type="submit" class="btn btn-default">
        <i class="fa fa-search"></i>
      </button>
    </form>

  </div>
  <div class="col-md-4">
    <%= link_to 'Nuevo Deportista', new_deportist_path, class: 'btn btn-success btn-lg btn-nuevo' %>
  </div>
</div>

<div class="row">
  <br/>
  <div class="col-md-11">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>#</th>
          <th>Nombre</th>
          <th>Edad</th>
          <th>IMC</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% if @deportists.present? %>
        <%= render @deportists %>
        <% else %>
        <tr>
          <th colspan=5>
            <p style="text-align:center">Aún no hay deportistas ingresados en el sistema.</p>
          </th>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/deportists/new.html.erb
<div class='row'>
  <div class='col-lg-12'>
    <div class='well bs-component'>
      <%= form_for @deportist, html: { class: 'form-horizontal' } do |f| %>
      <fieldset>
        <legend>
          Nuevo Deportista
        </legend>

        <div class="form-group">
          <%= f.label :number, 'Número:', class: 'col-sm-2 control-label' %>
          <div class='col-sm-10'>
            <%= f.text_field :number, class: 'form-control', placeholder: 'Número' %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :name, 'Nombre:', class: 'col-sm-2 control-label' %>
          <div class='col-sm-10'>
            <%= f.text_field :name, class: 'form-control', placeholder: 'Nombre' %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :age, 'Edad:', class: 'col-sm-2 control-label' %>
          <div class='col-sm-10'>
            <%= f.text_field :age, class: 'form-control', placeholder: 'Edad' %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :imc, 'IMC:', class: 'col-sm-2 control-label' %>
          <div class='col-sm-10'>
            <%= f.text_field :imc, class: 'form-control', placeholder: 'IMC' %>
          </div>
        </div>

        <%= f.submit 'Crear deportista', class: 'btn btn-success pull-right' %>
        <%= link_to 'Cancelar', deportists_path, class: 'btn btn-default pull-right' %>

      </fieldset>
      <% end %>
    </div>
  </div>
</div>

app/views/diet_plan_assignments/new.html.erb
<div class="row">
  <div class="col-md-12">
    <% if @diet_plan_assignment.errors.any? %>
      <div class="alert alert-danger">
        <ul>
          <% @diet_plan_assignment.errors.full_messages.each do |error| %>
          <li><%= error %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <h3><%= @deportist.name %> (#<%= @deportist.number %>)</h3>
    <hr>
  </div>
</div>

<div class="row">
  <div class="col-md-4">
    <h4>Planes dietarios actuales</h4>
    <% if @deportist.diet_plans.any? %>
      <dl>
        <dt>Principal</dt>
        <dd><%= @deportist.main_diet_plan.name %></dd>
      </dl>
      <h5>Secundarios</h5>
      <ul>
        <% @deportist.secondary_diet_plans.each do |dp| %>
        <li>
          <%= dp.name %>
        </li>
        <% end %>
      </ul>
    <% else %>
      <p> Actualmente no hay planes asignados. </p>
    <% end %>
  </div>
  <div class="col-md-4">
    <dl>
      <dt>Número</dt>
      <dd><%= @deportist.number %></dd>
      <dt>Noombre</dt>
      <dd><%= @deportist.name %></dd>
      <dt>Edad</dt>
      <dd><%= @deportist.age %></dd>
      <dt>IMC (Índice de Masa Corporal)</dt>
      <dd><%= @deportist.imc %></dd>
    </dl>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <h4>Asignar nuevo plan dietario</h4>
    <hr>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <%= form_for [@deportist, @diet_plan_assignment], html: { class: 'form-inline' } do |f| %>
      <div class="form-group col-md-4">
        <%= f.label :diet_plan, 'Plan:' %>
        <%= f.collection_select :diet_plan_id, @diet_plans, :id, :name %>
      </div>
      <div class="form-group col-md-4">
        <%= f.label :priority, 'Prioridad:' %>
        <%= f.select :priority, options_for_select(DietPlanAssignment.priorities) %>
      </div>

      <div class="form-group col-md-4">
        <%= f.submit 'Asignar Plan', class: 'btn btn-success pull-right' %>
        <%= link_to 'Cancelar', deportists_path, class: 'btn btn-default pull-right' %>
      </div>
    <% end %>
  </div>


</div>

app/views/diet_plans/_diet_plan.html.erb
<tr>
  <td><%= diet_plan.custom_id %></td>
  <td><%= diet_plan.name %></td>
  <td><%= diet_plan.goal %></td>
  <td><%= diet_plan.category.name %></td>

  <td><%= link_to confirm_deletion_diet_plan_path(diet_plan), class: 'btn btn-xs btn-danger' do %>
    <i class="fa fa-times"></i>
  <% end %></td>
</tr>

app/views/diet_plans/_meal_fields.html.erb
<div class="form-group nested-fields">
  <div class='col-sm-3'>
    <%= f.text_field :portion, class: 'form-control', placeholder: 'Porción' %>
  </div>

  <div class='col-sm-3'>
    <%= f.text_field :calories, class: 'form-control', placeholder: 'Calorías' %>
  </div>

  <div class='col-sm-2'>
    <%= f.select :day, options_for_select([['Lunes', 1], ['Martes', 2],
      ['Miercoles', 3], ['Jueves', 4], ['Viernes', 5], ['Sabado', 6],
      ['Domingo', 0]]), class: 'form-control' %>
  </div>

  <div class='col-sm-3'>
    <%= f.select :day_moment, Meal.day_moments, class: 'form-control'%>
  </div>

  <div class='col-sm-1'>
    <%= link_to_remove_association f, class: 'btn btn-danger' do %>
      <i class="fa fa-times"></i>
    <% end %>
  </div>
</div>

app/views/diet_plans/confirm_deletion.html.erb
<% if params[:action] == 'destroy' %>
  <div class="row">
    <div class="col-md-12">
      <div class="alert alert-danger">
        Existe un deportista que tiene asignado únicamente este plan.
      </div>
    </div>
  </div>
<% end %>

<div class="row">
  <div class="col-md-4">
    <h3>Plan: <%= @diet_plan.custom_id %></h3>

    <div class="alert alert-warning">
      <p><strong>Deportistas con este plan :</strong></p>
      <% if @diet_plan.deportists.any? %>
        <ul>
          <% @diet_plan.deportists.each do |d| %>
            <%= "#{d.name} (##{d.number})" %>
          <% end %>
        </ul>
      <% else %>
        Este plan no se encuentra asignado a ningún deportista.
      <% end %>
    </div>

    <div class="alert alert-danger">
      Seguro que lo desea borrar?
    </div>

    <%= link_to 'Cancelar', root_path, class: 'btn btn-default' %>
    <%= link_to 'Borrar', diet_plan_path(@diet_plan), class: 'btn btn-danger', method: :delete  %>
  </div>
  <div class="col-md-4">
    <dl>
      <dt>Nombre</dt>
      <dd><%= @diet_plan.name %></dd>
      <dt>Objetivo</dt>
      <dd><%= @diet_plan.goal %></dd>
      <dt>Categoría</dt>
      <dd><%= @diet_plan.category.name %></dd>
      <dt>Tipo de plan</dt>
      <dd><%= DietPlan::TYPES[@diet_plan.plan_type] %></dd>
      <dt>Rango Etáreo</dt>
      <dd>Desde <%= @diet_plan.from_age %> hasta <%= @diet_plan.to_age %></dd>
      <dt>Rango IMC</dt>
      <dd>Desde <%= @diet_plan.from_imc %> hasta <%= @diet_plan.to_imc %></dd>
    </dl>
  </div>
</div>

app/views/diet_plans/new.html.erb
<div class='row'>
  <% if @diet_plan.errors.any? %>
    <div class='col-lg-12'>
      <div class="alert alert-danger">
        <ul>
          <% @diet_plan.errors.full_messages.each do |error| %>
          <li><%= error %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>
  <div class='col-lg-12'>
    <div class='well bs-component'>
      <%= form_for @diet_plan, html: { class: 'form-horizontal' } do |f| %>
        <fieldset>
          <legend>
            Nuevo Plan Dietario
          </legend>

          <div class="form-group">
            <%= f.label :custom_id, 'ID:', class: 'col-sm-2 control-label' %>
            <div class='col-sm-10'>
              <% custom_id = @diet_plan.auto_generate_id %>
              <%= f.text_field :custom_id, value: custom_id,
                disabled: 'disabled', class: 'form-control' %>
                <%= f.hidden_field :custom_id, value: custom_id %>
            </div>
          </div>

          <div class="form-group">
            <%= f.label :name, 'Nombre:', class: 'col-sm-2 control-label' %>
            <div class='col-sm-10'>
              <%= f.text_field :name, class: 'form-control', placeholder: 'Nombre' %>
            </div>
          </div>
          <div class="form-group">
            <%= f.label :goal, 'Objetivo:', class: 'col-sm-2 control-label' %>
            <div class='col-sm-10'>
              <%= f.text_area :goal, class: 'form-control', placeholder: 'Objetivos' %>
            </div>
          </div>

          <div class="form-group">
            <%= f.label :category, 'Categorias:', class: 'col-sm-2 control-label' %>

            <div class='col-sm-10'>
              <%= f.collection_select :category_id, @categories, :id, :name,
                class: 'form-control' %>
            </div>
          </div>

          <div class="form-group">
            <%= f.label :plan_type, 'Tipo de plan:', class: 'col-sm-2 control-label' %>

            <div class='col-sm-10'>
              <%= f.select :plan_type, options_for_select(DietPlan.available_plan_types),
                  class: 'form-control' %>
            </div>
          </div>

          <div class="form-group">
            <%= f.label :from_age, 'Rango Etéreo:', class: 'col-sm-2 control-label' %>

            <div class='col-sm-4'>
              <%= f.text_field :from_age, class: 'form-control', placeholder: 'Desde' %>
              <span class="help-block">
                Si no se ingresa un rango de edad, se asume que es válido para cualquier edad.
              </span>
            </div>

            <div class='col-sm-4'>
              <%= f.text_field :to_age, class: 'form-control', placeholder: 'Hasta' %>
            </div>
          </div>

          <div class="form-group">
            <%= f.label :from_imc, 'Rango IMC:', class: 'col-sm-2 control-label' %>

            <div class='col-sm-4'>
              <%= f.text_field :from_imc, class: 'form-control', placeholder: 'Desde' %>
              <span class="help-block">
                Si no se ingresa un rango de IMC, se asume que es válido para cualquier IMC.
              </span>
            </div>

            <div class='col-sm-4'>
              <%= f.text_field :to_imc, class: 'form-control', placeholder: 'Hasta' %>
            </div>
          </div>


          <div class="form-group">
            <%= f.label :duration, 'Duración:', class: 'col-sm-2 control-label' %>

            <div class='col-sm-4'>
              <%= f.text_field :duration, class: 'form-control', placeholder: 'Duracion' %>
            </div>

            <div class='col-sm-4'>
              <%= f.select :duration_type, options_for_select(DietPlan.duration_types),
                class: 'form-control' %>
            </div>
          </div>

          <div class="form-group">
            <%= f.label :frequency, 'Frecuencia de ingestas:', class: 'col-sm-2 control-label' %>

            <div class='col-sm-10'>
              <%= f.select :frequency, options_for_select(DietPlan.frequencies),
                class: 'form-control' %>
            </div>
          </div>

          <legend>
            Ingestas
          </legend>

          <%= f.fields_for :meals do |meal| %>
            <%= render 'meal_fields', :f => meal %>
          <% end %>

          <div class='agregar-ingesta'>
            <%= link_to_add_association 'Agregar Ingesta', f, :meals, class: 'btn btn-primary' %>
          </div>

          <legend>
          </legend>

          <%= f.submit 'Guardar plan dietario', class: 'btn btn-success pull-right' %>
          <%= link_to 'Cancelar', root_path, class: 'btn btn-default pull-right' %>

        </fieldset>
      <% end %>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class="row">
  <div class="col-md-4">
    <h3>Planes dietarios</h3>
  </div>
  <div class="col-md-4">
    <form method="get" action="/" class="form-inline btn-nuevo" role="form">
      <div class="form-group">
        <div class="input-group">
          <input type="text" name="filter" value="<%= params[:filter] %>"
            class="form-control" placeholder="Buscar">
        </div>
      </div>

      <button type="submit" class="btn btn-default">
        <i class="fa fa-search"></i>
      </button>
    </form>

  </div>
  <div class="col-md-4">
    <%= link_to 'Nuevo Plan Dietario', new_diet_plan_path, class: 'btn btn-success btn-lg btn-nuevo' %>
  </div>
</div>

<div class="row">
  <br/>
  <div class="col-md-11">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Id</th>
          <th>Nombre</th>
          <th>Objetivo</th>
          <th>Categoría</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% if @diet_plans.present? %>
          <%= render @diet_plans %>
        <% else %>
        <tr>
          <th colspan=5>
            <p style="text-align:center">No se encontraron registros.</p>
          </th>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Módulo de Gestión Dietaria</title>
  <%= stylesheet_link_tag    'application',
    'bootstrap.min', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'Módulo de Gestión Dietaria', root_path, class: 'navbar-brand' %>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li class="<%= params[:controller] == 'home' ? 'active' : '' %>"><%= link_to 'Planes Dietarios', root_path %></li>
          <li class="<%= params[:controller] == 'deportists' ? 'active' : '' %>"><%= link_to 'Deportistas', deportists_path %></li>
        </ul>

      </div><!--/.nav-collapse -->
    </div>
  </nav>

  <div id="main-content" class="container">
    <%= yield %>
  </div>

  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
</body>
</html>